version: '3'

services:
  ssdt:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes: ["./SSDT:/opt/SSDT"]
    environment:
      PORT: "5000"
      FLASK_DEBUG: "true"
    ports:
      - "5000:5000"
